[editor]
line-number = "relative"
mouse = false
scrolloff = 8

[editor.auto-save.after-delay]
enable = true

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "underline"

[editor.lsp]
snippets = true

[keys.insert.j]
j = ["normal_mode"]

